### PR TITLE
Interface reorg plus Sonar fixes

### PR DESCRIPTION
**Pull request by jmsjr**
**Summary**
- Extract and create interfaces with methods that are common to both 2D and 3D ( e.g. Vectorf, FabrikJoint, FabrikBone, FabrikChain, FabrikStructure, BaseBoneConstraintType )
- Have existing classes implement these new interfaces
- Also extracted out enum BoneConnectionPoint and use this instead of BoneConnectionPoint2D and BoneConnectionPoint3D, since they both have the same values ( START and END )
- Plus lots of Sonar fixes, some low-hanging fixes ( e.g. formatting ), but also some bugfixes in the use of static and equality and comparison on floats

**Build**
Last build result from master ( build#32 ) passed:
https://travis-ci.org/jmsjr/caliko/branches

**Sonar**
Last sonar report remove existing bugs plus reduced the number of vulnerabilities and code smells. The new code smells were considered "new" but they were simply from the existing demo code that were re-factored into separate classes, which Sonar considered "new":
https://sonarqube.com/dashboard?id=au.edu.federation.caliko%3Acaliko-aggregate

### CODE REVIEW

**Comment by jmsjr** [comment]
Hi,

Thanks for the feedback. I'll try to address each item you have in here, though it would have been better if you have gone to the diff changes ( https://github.com/FedUni/caliko/pull/7/files/3e73505d81628132c4602c2502f0bd79b91aa9d4 ) and hover the mouse over to the line that you are reviewing, and there should be a blue plus sign where you can add the comment / review.

> You want to use a ReflectiveOperationException instead of an Exception because we now have things shared between 2D/3D?

That's because the method makeDemoStructure2D()/makeDemoStructure3D() will only throw an IllegalAccessException or an InstantiationException .. both of which is a ReflectiveOperationException.

> You want every axis to have unique VAO and VBOs - even when they hold the same data across all instances? I don't see the point. Same with matrix and vertex float buffers... they're re-usable.

I see your point. It was not obvious to me about the intention. 
This was basically a result of the following:
https://sonarqube.com/coding_rules#rule_key=squid%3AS3010

Question:
Is the block of code inside the 

`if (!shaderInitialised)
`
... meant to be initialised once per VM instead of once per instance of Axis, Circle3D, FabrikModel3D, Line2D, Line3D, Point2D, Point3D, etc ??

> Looking at:
> 
> Vec2f rotatedUV = Vec2f.rotateDegs(defaultUV, loop * numBones);
> Vec2f rotatedUV = Vec2f.rotateDegs(defaultUV, (float)loop * numBones);
> You're just casting loop to a float, not the result of the multiplication to a float - but even if it was encased in brackets it would just be casting the result of multiplying two ints together to a float. Why?

This is described in here:
https://sonarqube.com/coding_rules#rule_key=squid%3AS2184

> And:
> 
> VERTEX_COMPONENTS * Float.BYTES); // Offset
> (long)VERTEX_COMPONENTS * Float.BYTES); // Offset
> Is 3.2 billion vertex components not enough that you have to cast it to 8 bytes?

Same as the previous one:
https://sonarqube.com/coding_rules#rule_key=squid%3AS2184


> Then:
> 
>   mAttributeMap = new HashMap<String, Integer>();
>   mUniformMap   = new HashMap<String, Integer>();
>   mAttributeMap = new HashMap<>();
>   mUniformMap   = new HashMap<>();
> We know the type of the hashmap and it'll never change, so why change that?

https://sonarqube.com/coding_rules#rule_key=squid%3AS2293



> C/V/B for Constraint/Vector/Bone? I might be a little too old-school for that to sit nicely just yet, but I think I could get used to it with time.

I presume you are referring to the generic parameters. I could not come up a proper letters as there is more than one type in some cases like in the FabrikChain interface, although there is a convention defined  under "Type Parameter Naming Conventions" of
https://docs.oracle.com/javase/tutorial/java/generics/types.html

Suggestions welcome

> Why do you change these?:
> 
> private List mChains = new ArrayList();
> private List mChains = new ArrayList<>();

Same as the other change above:
https://sonarqube.com/coding_rules#rule_key=squid%3AS2293


> if (right - left == 0.0f) { throw new IllegalArgumentException("(right - left) cannot be zero."); }
> if (Float.compare(right - left,0.0f)==0) { throw new IllegalArgumentException("(right - left) cannot be zero."); }
> The above is so much better using your threshold/compare... Yuck. Never compare floats/doubles without one. That one might have just creeped in one day. Good catch.

Yup ... but, despite that change, I thought that Float.compare() might still be missing a tolerance.

**If assuming** that you agree to most the explanations, possibly the only real change needed from the pull request are the changes ( from static to non-static ) in Axis, Point2D, Point3D, Line2D, Line3D, ... re: your comment about: 

> You want every axis to have unique VAO and VBOs - even when they hold the same data across all instances? I don't see the point. Same with matrix and vertex float buffers... they're re-usable.

where I mentioned:

https://sonarqube.com/coding_rules#rule_key=squid%3AS3010

Would it be palatable if I undo those specific changes and submit a separate pull request for them ?

I'll shortly put up the README.md changes

Separate question: Do you have SonarLint installed with Eclipse ? If you don't, I would suggest that you install it ( available from Help -> Eclipse Marketplace ). It mostly gives out the same issues / warnings that the on-line Sonar report would give out. Just open one of the Java classes, and then SonarLint should show you automatically the issues that it finds ( Show -> View -> Other -> SonarLint -> SonarLint On the Fly )

**Comment by jmsjr** [comment]
Okay, made 2 additional commits:

1. README.md changes

2. Change back the properties that were originally static which we changed to non-static back to static .. but this time, they are initialised in a static initialiser instead of being initialised in a constructor. I also have to add private static methods to update these static properties due to:

https://sonarqube.com/coding_rules#rule_key=squid%3AS2696

However, I admit that I am just tricking Sonar in this case so as not to complain as the real issue in question is still possible ( e.g. multiple-threads calling draw calling the private static method ).

This should hopefully address your concern about:

> You want every axis to have unique VAO and VBOs - even when they hold the same data across all instances? I don't see the point. Same with matrix and vertex float buffers... they're re-usable.

as the behaviour is now the same as the original, prior to the pull request.

**Comment by alansley** [comment]
Pull request merged - great job! =D I didn't know about clicking the blue arrow to provide feedback on specific changes, sorry - I'll know for next time.

I don't have sonar installed in Eclipse, but will go and do that now - it's pretty useful to have by the looks.

The static "shaderInitialised" flag is just meant to compile and set up the shaders when the first instance of something like an Axis or whatnot is created - after that we know the shader's all set up and ready for use so we don't have to recompile/recreate the shader for each instance. Without this we might be doing a lot of shader teardown and setup for no reason if creating and destroying drawables.

Cheers,
Al

**Comment by alansley** [comment]
Hi there,

There was a request for a Java 7 version of Caliko ( https://github.com/FedUni/caliko/issues/8 ) - so I was thinking about it and wondering about the best way to implement. I don't think a branch is the best way to go as branches are meant to merge in eventually, and this may never. 

So, other ways of doing it might include using a Git worktree, or via the maven replacer plugin? The problem with the latter is that the Caliko visualisation/demo packages use lambda functions which require Java 8 (or perhaps the retrolambda plugin - https://github.com/orfjackal/retrolambda).

However, I could go back and write standard functions to replace the lambda functions, and then it's just Float.BYTES which needs to be token-replaced in the Java 7 version...

Not asking you to do this - just wondered if you had any thoughts about the best way to go about it as your Git & Maven knowledge is way ahead of my own. Just bought the latest Humble Books Bundle (Linux) so I can try to plough my way through Pro Git 2nd Edition and catch up!

Any thoughts gratefully appreciated =D

-Al

**Pull request merged**
