### PR TITLE
Bugfix/issue 11

### PR DESCRIPTION
**Pull request by jmsjr**
Attempt to address issue discussed at https://github.com/FedUni/caliko/issues/11 ... by constraining the end-effector bone on forward pass.

### CODE REVIEW

**Comment by alansley** [comment]
Oooh... this is close, but it's not quite there. If you try the 2nd demo (unconstrained chain) you'll see the end-effector bone folds in sharply. Also, if you look at the 7th demo and leave the target bang in middle of the window then it toggles between alternate left/right solutions.

In the forward pass end-effector bone handling section your innerBoneInnerToOuterUV vector should be called **innerBoneOuterToInnerUV** because it goes from the outside (target/'end') to inside ('start'). The direction is correct, but the name is wrong.

I'll experiment with it a little and see what I can come up with. I think we're close, and it'll only be a small change required to get this working great.

**Comment by alansley** [comment]
And by Jove - five minutes later and I've cracked it! We need to use the constraints of this bone (not the inner bone), and constrain **this** bone about the baseline of the inner bone UV.

Try replacing the section around 868 to 906 with this, give it a crack and let me know what you think:

`			else // If we are working on the end effector bone ...
			{
				// Snap the end effector's end location to the target
				mChain.get(loop).setEndLocation(target);
				
				// Get the UV between the target / end-location (which are now the same) and the start location of this bone
				Vec2f thisBoneOuterToInnerUV = mChain.get(loop).getDirectionUV().negated();
				
				Vec2f constrainedUV;
				if (loop > 0) {
					// The end-effector bone is NOT the basebone as well
					// Get the inner-to-outer unit vector of the bone further in
					Vec2f innerBoneOuterToInnerUV = mChain.get(loop-1).getDirectionUV().negated().normalise();
					
					// Constrain the angle between the this bone and the inner bone
					// Note: On the forward pass we constrain to the limits imposed by the first joint of the inner bone.
					float clockwiseConstraintDegs     = mChain.get(loop).getJoint().getClockwiseConstraintDegs();
					float antiClockwiseConstraintDegs = mChain.get(loop).getJoint().getAnticlockwiseConstraintDegs();
					
					// Params: directionUV, baselineUV, clockwise, anticlockwise
					constrainedUV = Vec2f.getConstrainedUV( thisBoneOuterToInnerUV, innerBoneOuterToInnerUV, clockwiseConstraintDegs, antiClockwiseConstraintDegs);
					
				} else {
					// There is only one bone in the chain, and the bone is both the basebone and the end-effector bone.
					constrainedUV = thisBoneOuterToInnerUV;
				}
								
				// Calculate the new start joint location as the end joint location plus the outer-to-inner direction UV
				// multiplied by the length of the bone.
				Vec2f newStartLocation = mChain.get(loop).getEndLocation().plus( constrainedUV.times(boneLength) );
				
				// Set the new start joint location for this bone to be new start location...
				mChain.get(loop).setStartLocation(newStartLocation);

				// ...and set the end joint location of the bone further in to also be at the new start location.
				if (loop > 0) { 
				  mChain.get(loop-1).setEndLocation(newStartLocation);
				}
			}
`

**Comment by jmsjr** [comment]
Updated pull request as per your review. I did see alternating between left / right solutions on demo 2 and 7 ... and here I thought it was already like that even before the fix ... Tried it again on master branch, and it did not had that behaviour .. .Must have been tired yesterday.

**Comment by alansley** [comment]
Brilliant! Thanks, Jesus. Merge accepted & incorporated!

Because this change modifies core behaviour in a beneficial manner I'll generate a new release for it as well =D

**Pull request merged**
