### PR TITLE
Maven reorg

### PR DESCRIPTION
**Pull request by jmsjr**
**Summary**
This started off as a fix for running the demo in Eclipse of not being able to load pyramid.obj, and ended-up being a reorganisation of the structure to be more compliant with the "Maven way".

There are no functional changes and only a few Java code changes outlined below.

**Restructure changes**
The restructure includes:

Move pyramid.obj to src/main/resources/pyramid.obj
Move java source files within each Maven module from src/ to src/main/java
Update pom.xmls and remove build/sourceDirectory entry, so that it defaults to src/main/java and not src/
Update .gitignore to exclude target and other Eclipse settings from being committed to git
Make caliko-aggregate as parent POM
Define the use of Java 1.8 in parent POM so that it gets inherited on all child modules
Set a single version defined from parent POM. Currently set to 1.3.1
Move PDF, XSLX files to src/site/docs
Create new module caliko-distribution to generate Javadoc and source artifacts. Remove them from parent POM
Move code from perf-test ( which was not in any Maven module ) to a JUnit test in caliko module
Add surefire and failsafe plugins into build
Java code changes
The Java code changes are:
A) Remove commented-out code from from CalikoDemo3D,
B) Change in perf-test/Application.java ( renamed to ApplicationPerfTest.java ) to call solveForTarget() instead of updateForTarget() as the code was failing build compilation. Furthermore, the output text is written out to target/.

**Build Integration**
Integration with Travis-CI and Sonar

https://travis-ci.org/jmsjr/caliko
https://travis-ci.org/jmsjr/caliko/branches
https://sonarqube.com/dashboard?id=au.edu.federation.caliko%3Acaliko-aggregate

**Other**
Next pull request will be to address Sonar issues

### CODE REVIEW

**Comment by alansley** [comment]
Hi there,

Thanks for this. I don't know a great deal about maven so just muddled through when doing this, and hadn't used Travis CI or SonarQube before so I'm finding it quite interesting.

I've merged your pull request, however now it doesn't seem to create a zip I can use for a release - previously it would dump the contents of the RELEASE folder into caliko.zip and then I could make that file the pre-packaged release. The only zip now is the caliko-distribution-1.3.1-sources.zip file which as it sounds just has the source code without any of the javadoc, user docs etc.

Thoughts?

**Comment by jmsjr** [comment]
Hi,

I can certainly re-add another assembly to generate the full distribution.zip ( with binaries, docs, etc ). Will do this in another pull request .... probably #7 as I have just made another pull request #6 for the demo-reorg.

One of the objective was to push the release artifacts to the Maven central repository so that anyone can add the adding the caliko dependency in their own Maven projects which will automatically download the caliko artifacts from the Maven central repository. At that point, the need to have a distribution zip with binaries, docs, etc is sort of redundant.

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

Meanwhile, I would be addressing some of the Sonar issues, plus probably an increase in the code coverage before uploading to the Maven central repository ... so that we have a quality gate and no new issues are introduced with each release.

Finally, I have some ideas and plans to have the caliko output the result of the IK algorithm so that it can be feed to an external source ( e.g. an actual robotic arm, etc ) ... but that's after adding all the build automation / sonar fixes etc.

P.S. I am also from down under ( Central Coast ) so can only work on this on my spare time after hours.

**Comment by alansley** [comment]
Thanks! Have accepted the #6 pull request, and appreciate the re-addition of the distribution zip.

While it'll certainly be good to have Caliko in the Maven central repository, I feel that allowing developers who might choose not to use Maven and just want the lib as a standalone version is important too.

In terms of quality, and not janking the algorithm, it would probably be worth having something similar to the perf-test (which uses a fixed random seed for reproducability) - then each demo maybe runs for a 1000 'frames' (even without visualiation) and dumps the final chain config to a file. This file can then be SHA-1'd and the hash compared to the same for future runs - this way we know it's not only compiling but functioning identically for a given set of data.

It's not critical by any means, but would likely be useful down the track. Thoughts welcome as ever!

-Al

**Comment by jmsjr** [comment]
1) distribution - Point taken. We can keep it.

2) With regards to quality .. that is actually the next thing I am going to do. I wanted to fix / address some of the Sonar issues that were raised. But to do that, need a way to ensure that we are not breaking anything. Instead of comparing the final chain config from a text file, I am thinking of testing / comparing the config at each iteration / update to the target. 

To do this, will have to implement equals() and hashCode() at the bone and chain levels, allowing for a pre-defined epsilon when comparing the config since we are dealing with floats. Apart from equals() and hashCode(), also need a way to define that a structure is "the same" as another structure regardless of each position of each chain.

Thus:
1) theSame() to compare two structures regardless of position ( e.g. two pictures of a person is the same, one picture standing, the other picture running )
2) equals() would be when the structure is "the same" as another structure, but also the position of each chain in the structure is the same. 

Add some interfaces and generics to the mix that would be implemented by the existing class, without changing the algorithm ... and then I can start addressing the Sonar issues.

This may take awhile.

- Jesus

**Pull request merged**
